# Podstawy Sztucznej Inteligencji 2020/2021


Prosze uzupelnic kod tam gdzie znajduje napis `YOUR CODE HERE` lub 'YOUR ANSWER HERE'.

Warto zresetowac 'kernel' i sprawdzic czy caly notatnik uruchamiany od poczatku nie daje bledow.

---

## Liniowa analiza dyskryminacyjna Fishera


Idea - maksymalizacja stosunku wariancji:


$$ \frac{\sigma_b^2}{\sigma_w^2}$$


Niech $S_b$ będzie macierzą kowariancji (lub scatter matrix) pomiędzy klasami

$$S_b= \sum_c N_c \left(\mu_c-\mu\right) \left(\mu_c-\mu\right)^T$$

gdzie $\mu_c$ oznacza średni wektor cech w obrębie jednej klasy $c$ o liczebności $N_c$.


Niech $S_{wc}$ będzie macierzą kowariancji (lub scatter matrix) wewnątrz  klasy:

$$S_{wc}= \frac{1}{N_c-1}\sum_{i\in c} \left(x_i-\mu_c\right) \left(x_i-\mu_c\right)^T$$

gdzie $\mu_i$ oznacza średni wektor cech w obrębie jednej klasy o liczebności $N_c$.

Interesuje nas suma takich macierzy:

$$S_w= \sum_c S_{wc}  = \sum_c\frac{1}{N_c-1}\sum_{i\in c} \left(x_i-\mu_c\right) \left(x_i-\mu_c\right)^T$$


Analiza dyskryminacyjna Fishera poszukuje takich wektorów $\mathbf{w}$, które maksymalizują:

$$ J = \frac{\mathbf{w}^T S_b\mathbf{w}}{\mathbf{w}^T S_w\mathbf{w}}.$$

Ponieważ $J$ jest niezmiennicze względem skalowania $\mathbf{w}\to\alpha\mathbf{w}$, to możemy ograniczyć się do takich $\mathbf{w}$, że $\mathbf{w}^T S_w\mathbf{w}=1$. Wtedy mamy zagadnienie minimalizacyjne:

$$  \mathrm{min}_\mathbf{w}  -\mathbf{w}^T S_b\mathbf{w} \\
  \mathbf{w}^T S_w\mathbf{w} = 1 $$

Stosując mnożniki Lagrange'a mamy:

$$L = -\frac{1}{2} \mathbf{w}^T S_b\mathbf{w} + \frac{1}{2} \lambda \left(\mathbf{w}^T S_w\mathbf{w} - 1\right)  $$

$$
\frac{\partial L}{\partial \mathbf{w}} = -S_b\mathbf{w} + \lambda  S_w\mathbf{w} = 0
$$

czyli:

$$
 S_b\mathbf{w} = \lambda  S_w\mathbf{w} 
$$

Powyższe wyrażenie jest tzw. uogólnionym zagadnieniem własnym. Jeśli istnieje macierz odwrotna $S_w^{-1}$ to można je sprowadzić do:


$$
 S_w^{-1} S_b\mathbf{w} = \lambda  \mathbf{w} 
$$




In [1]:
%matplotlib inline 
import matplotlib.pyplot as plt
import numpy as np 

In [2]:
from sklearn.datasets import load_wine
data = load_wine()
X = data.data
y = data.target

In [3]:
X.shape

(178, 13)

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

### Wyznacz liczbę klas 

In [6]:
classes = [2,3,4,5,6] # niepoprawne 

# YOUR CODE HERE
classes = np.unique(y)
# raise NotImplementedError()


In [7]:
assert len(classes) == 3

### Oblicz macierze kowariancji wewnątrzklasowe

Oblicz dla przykładów z każdej klasy macierz kowariancji (np. użyj `np.cov`) a nastęmnie ich sumę $S_w$.

$$S_w= \sum_c\underbrace{\frac{1}{N_c-1}\sum_{i\in c} \left(x_i-\mu_c\right) \left(x_i-\mu_c\right)^T}_{\mathrm{np.cov}}$$



In [28]:
y==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [36]:
Sw = None
# YOUR CODE HERE
Sw = sum([np.cov(X[y==i].T) for i in classes])
# raise NotImplementedError()

In [37]:
assert Sw.shape == (13,13)
np.testing.assert_allclose(Sw[1,2],0.055372, rtol=1e-3)

### Oblicz macierz kowariancji pomiędzy klasami


Niech $S_b$ będzie macierzą kowariancji (lub  scatter matrix) pomiędzy klasami

$$S_b= \sum_c N_c \left(\mu_c-\mu\right) \left(\mu_c-\mu\right)^T$$

gdzie $\mu_c$ oznacza średni wektor cech w obrębie jednej klasy $c$ o liczebności $N_c$.



In [40]:
mu_c = [np.mean(X[y==c_], axis=0) for c_ in classes] 

In [41]:
mu = np.mean(X, axis=0)
mu

array([1.30006180e+01, 2.33634831e+00, 2.36651685e+00, 1.94949438e+01,
       9.97415730e+01, 2.29511236e+00, 2.02926966e+00, 3.61853933e-01,
       1.59089888e+00, 5.05808988e+00, 9.57449438e-01, 2.61168539e+00,
       7.46893258e+02])

In [46]:
mu = np.mean(X, axis=0)

# YOUR CODE HERE
#np.dot(mu,mu)



Sb = sum([np.sum(y==c_)*np.outer(np.mean(X[y==c_], axis=0)-mu,np.mean(X[y==c_], axis=0)-mu) for c_ in classes])
np.outer(mu,mu)
# raise NotImplementedError()
                                                                      
                                      

array([[1.69016068e+02, 3.03739719e+01, 3.07661816e+01, 2.53446317e+02,
        1.29670209e+03, 2.98378790e+01, 2.63817597e+01, 4.70432474e+00,
        2.06826685e+01, 6.57582943e+01, 1.24474344e+01, 3.39535241e+01,
        9.71007392e+03],
       [3.03739719e+01, 5.45852345e+00, 5.52900766e+00, 4.55469791e+01,
        2.33031056e+02, 5.36218189e+00, 4.74108076e+00, 8.45416826e-01,
        3.71689391e+00, 1.18174598e+01, 2.23693538e+00, 6.10180677e+00,
        1.74500281e+03],
       [3.07661816e+01, 5.52900766e+00, 5.60040202e+00, 4.61351131e+01,
        2.36040114e+02, 5.43142208e+00, 4.80230086e+00, 8.56333430e-01,
        3.76488900e+00, 1.19700550e+01, 2.26582023e+00, 6.18059750e+00,
        1.76753548e+03],
       [2.53446317e+02, 4.55469791e+01, 4.61351131e+01, 3.80052835e+02,
        1.94445636e+03, 4.47430865e+01, 3.95604981e+01, 7.05432209e+00,
        3.10144842e+01, 9.86071781e+01, 1.86654230e+01, 5.09146600e+01,
        1.45606421e+04],
       [1.29670209e+03, 2.33031056e+

In [ ]:
np.testing.assert_allclose(Sb[3,1],117.92843036,rtol=1e-3)
assert Sb.shape == (13,13)


### Wartości własne

Oblicz wartości własne macierzy:  

$$
 S_w^{-1} S_b
$$

i odpowiadające im wektory własne.

1. Zastosuj ` np.linalg.eig`, oraz `np.linalg.inv`.
2. Otrzymane wartości mogą zawierać część urojoną, użyj np. `np.real_if_close` by wyzerować części urojone.


In [ ]:
lam, v = None, None
# YOUR CODE HERE
raise NotImplementedError()

lam

In [ ]:
assert lam.shape ==(13,)
np.testing.assert_allclose(np.max(lam), 546, rtol=1e-2 )

### Operator rzutowania na podprzestrzeń


Posortuj wektory własne według malejących wartości własnych. 

Zbuduj operator $W$ będący macierzą $(2,13)$ składający się z dwóch wektorów własnych odpowiadających największym wartościom własnym.

In [ ]:
idx = [1,2] # niepoprawne 
# YOUR CODE HERE
# raise NotImplementedError()
idx = [1,2] 
idx = np.argsort(lam)[-2:][::-1]

In [ ]:
np.testing.assert_allclose(lam[idx],[546.41649425, 243.23261924],rtol=1e-2)

In [ ]:
W = None 

# YOUR CODE HERE
W = np.real_if_close(v[:,idx])
W = W.T
# raise NotImplementedError()



In [ ]:
np.testing.assert_allclose(np.abs(W[:,:3]),[[0.13138292,  0.05322257, 0.12283844],[0.24550374, 0.07699549, 0.67155662]], rtol=1e-2)

assert W.shape == (2,13)

### Wizualizacja wyniku

Operacja rzutowania może być w numpy zapisana jako `X.dot(W.T)`, więc w zredukowanej przestrzeni mamy:

In [ ]:
plt.scatter( X.dot(W.T)[:,0],X.dot(W.T)[:,1],c=y)

### Porównaj wynik z `sklearn`

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis(n_components=2, solver='eigen')
X_r2 = lda.fit(X, y).transform(X)
plt.scatter( X_r2[:,0],X_r2[:,1],c=y)